# This docker-compose file is used to run the project's published image
#
# Usage: docker-compose up [-d]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: '3.4'

networks:
  reaction:
    external:
      name: reaction.localhost

services:
  api:
    image: reactioncommerce/reaction:3.4.0
    depends_on:
      - mongo
    env_file:
      - ./.env
    networks:
      default:
      reaction:
    ports:
      - "3000:3000"

  mongo:
    image: mongo:4.2.0
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
    networks:
      default:
      reaction:
    ports:
      - "27017:27017"
    volumes:
      - mongo-db4:/data/db

volumes:
  mongo-db4:
