# This docker-compose file is used to run the reaction app in docker for development
# The local files are mounted into the created container.
# Usage: docker-compose up [-d]

version: '3.4'

networks:
  api:
    external:
      name: api.reaction.localhost
  auth:
    external:
      name: auth.reaction.localhost
  streams:
    external:
      name: streams.reaction.localhost

services:

  reaction:
    build:
      context: .
      target: meteor-dev
    command: bash -c "time meteor npm install --no-audit && node ./.reaction/waitForMongo.js && reaction"
    depends_on:
      - mongo
    env_file:
      - ./.env
    networks:
      default:
      api:
      auth:
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/reaction/src:cached
      - reaction_node_modules:/opt/reaction/src/node_modules # do not link node_modules in, and persist it between dc up runs

  mongo:
    image: mongo:3.6.3
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
    networks:
      default:
      streams:
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
  reaction_node_modules:
